version: 2.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release

environment:  
  GITHUB_TOKEN:
    secure: AD1z81FqZlvGkCEyDzJ3g6sIJ93ecUE9EuqfUxc4CMiFGW139pWZk+/huuTY5jzG  

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- cmd: nuget restore

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: normal

after_build:
- xcopy C:\projects\cepaberto\CEPAberto\bin\Release\*.* C:\projects\cepaberto\src\
- rd /s /q C:\projects\cepaberto\CEPAberto\bin\Release\
- cd C:\projects\cepaberto\
- 7z a -tzip -mx9 "CEPAberto.v%APPVEYOR_BUILD_VERSION%.zip" src

artifacts:
- path: CEPAberto.v%APPVEYOR_BUILD_VERSION%.zip
  name: ZipFile

deploy:

- provider: Environment
  on:
   branch: master
  name: NuGet

- provider: GitHub
  on:
   branch: master
  tag: $(appveyor_build_version)
  auth_token: $(GITHUB_TOKEN)
  force_update: true
  artifact: ZipFile
