version: 3.0.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release

environment:
  SOLUTION_NAME: CEPAberto
  SONAR_TOKEN: 
    secure: FZall4UDTaaxIAcigp9Z4pmSKa1YKxNB/ahexpxsRzKjIOsXBU/Ge1PoU2Qgt1zK
  GITHUB_TOKEN: 
    secure: AD1z81FqZlvGkCEyDzJ3g6sIJ93ecUE9EuqfUxc4CMiFGW139pWZk+/huuTY5jzG
  CODACY_PROJECT_TOKEN:
    secure: jB+7YloyEU1QHmoy/MvUkkaH6cucrrlLnFQww11QxR47GXxpT31wnsDPghqwdIs0

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

init:
- SET JAVA_HOME=C:\Program Files\Java\jdk19
- SET PATH=%JAVA_HOME%\bin;%PATH%

before_build:
- ps: $env:SONAR_PROJECT = "$env:APPVEYOR_REPO_NAME" -replace "/","_"
- ps: $env:SONAR_ORGANIZATION = "$env:APPVEYOR_REPO_NAME" -replace "/.*$","-github"
- cmd: nuget restore
- cmd: choco install "sonarscanner-msbuild-net46" -y
- cmd: choco install opencover.portable
- cmd: choco install codecov
- cmd: curl -L https://github.com/codacy/codacy-coverage-reporter/releases/latest/download/codacy-coverage-reporter-assembly.jar > ./codacy-test-reporter.jar

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: normal

build_script:
- ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { &
    SonarScanner.MSBuild.exe begin 
    /k:"$env:SONAR_PROJECT" 
    /o:"$env:SONAR_ORGANIZATION" 
    /d:sonar.branch.name="$env:APPVEYOR_REPO_BRANCH"
    /d:sonar.host.url="https://sonarcloud.io" 
    /d:sonar.login="$env:SONAR_TOKEN" 
    /v:"$env:APPVEYOR_BUILD_NUMBER" 
    /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" 
    /d:sonar.coverage.exclusions="**/$env:SOLUTION_NAME.Tests/**,**/*Tests.cs" 
    /d:sonar.cs.opencover.reportsPaths="$env:CD\$env:SOLUTION_NAME.Tests\coverage.opencover.xml"
    }'
- ps: 'if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { &
    SonarScanner.MSBuild.exe begin
    /k:"$env:SONAR_PROJECT" 
    /o:"$env:SONAR_ORGANIZATION" 
    /d:sonar.pullrequest.key="$env:APPVEYOR_PULL_REQUEST_NUMBER"
    /d:sonar.host.url="https://sonarcloud.io" 
    /d:sonar.login="$env:SONAR_TOKEN" 
    /v:"$env:APPVEYOR_BUILD_NUMBER" 
    /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" 
    /d:sonar.coverage.exclusions="**/$env:SOLUTION_NAME.Tests/**,**/*Tests.cs" 
    /d:sonar.cs.opencover.reportsPaths="$env:CD\$env:SOLUTION_NAME.Tests\coverage.opencover.xml"
    }'
- msbuild -m "%SOLUTION_NAME%.sln" /property:Configuration=Release
- coverlet %SOLUTION_NAME%..Tests\bin\Release\%SOLUTION_NAME%..Tests.dll 
--output "%SOLUTION_NAME%..Tests\"
--target "vstest.console.exe"
--targetargs "%SOLUTION_NAME%..Tests\bin\Release\$%SOLUTION_NAME%..Tests.dll"
--format opencover
- codecov -f "%CD%\%SOLUTION_NAME%.Tests\coverage.opencover.xml"
- java 
 -jar 
 ./codacy-test-reporter.jar report 
 -l CSharp 
 -t %CODACY_PROJECT_TOKEN% 
 -r "%CD%\%SOLUTION_NAME%.Tests\coverage.opencover.xml"
- SonarScanner.MSBuild.exe end /d:sonar.login="%SONAR_TOKEN%"

after_build:
- xcopy %APPVEYOR_BUILD_FOLDER%\%SOLUTION_NAME%\bin\Release\*.* %APPVEYOR_BUILD_FOLDER%\src\

- rd /s /q %APPVEYOR_BUILD_FOLDER%\%SOLUTION_NAME%\bin\Release\

- cd %APPVEYOR_BUILD_FOLDER%

- 7z a -tzip -mx9 "$%SOLUTION_NAME%.v%APPVEYOR_BUILD_VERSION%.zip" src

artifacts:
- path: "%SOLUTION_NAME%.v%APPVEYOR_BUILD_VERSION%.zip"
  name: ZipFile

deploy:

- provider: Environment
  on:
   branch: master
  name: NuGet

- provider: GitHub
  on:
   branch: master
  tag: $(appveyor_build_version)
  auth_token: $(GITHUB_TOKEN)
  force_update: true
  artifact: ZipFile
